# Generated by Django 3.0.4 on 2020-03-11 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='facebook_id',
            new_name='google_id',
        ),
    ]
