# Generated by Django 3.0.4 on 2020-03-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200311_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_password',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
