# Generated by Django 3.0.4 on 2020-03-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_google_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
